[package]
name = "rawspeed"
version = "0.1.0"

[dependencies]
libc = "0.2"
rawspeed-sys = { path = "rawspeed-sys", version = "0.1.0" }
failure = "0.1"
tempdir = "0.3"
lazy_static = "1.0"
ndarray = "0.11"

[dev-dependencies]
bencher = "0.1"
reqwest = "*"

[[bench]]
name = "example"
harness = false
